[pr_reviewer]
extra_instructions="""\
- React ファイルのルートタグに従って、以下の通りレビュー観点を追加してください.
- ファイル全体について、行数が多い (コメント行を含まずに 300 行を超える) 場合、分割可能かどうかの観点をレビューに含め、可能であれば、指摘してください.
- テストコードについて、推奨されるテストケースであるかどうかの観点をレビューに含め、可能であれば、指摘してください.

[pr_code_suggestions]
extra_instructions="""\
- React ファイルのルートタグに従って、以下の通りレビュー観点を追加してください.
- ファイル全体について、行数が多い (コメント行を含まずに 300 行を超える) 場合、分割可能かどうかの観点をレビューに含め、可能であれば、指摘してください.
- テストコードについて、推奨されるテストケースであるかどうかの観点をレビューに含め、可能であれば、指摘してください.