[pr_reviewer]
extra_instructions="""\
1. 【最優先】Google Javascript style guideに従って、次の違反を指摘してください:
   - インデントやスペースの不適切な使用
   - 命名規則の違反
   - 一貫性のないコードスタイル
2. 【重要】ファイル全体の行数が多い (コメント行を含まずに 300 行を超える) 場合、次の観点で分割可能かどうかを確認し、可能であれば指摘してください:
   - コンポーネントや関数の単一責任の原則が守られているか？
   - 重複したロジックがないか？
   - コードの可読性が保たれているか？
3. 【重要】テストコードについて、次の観点でレビューを行い、必要に応じて指摘してください:
   - 主要なユースケースがカバーされているか？
   - エッジケースがテストされているか？
   - 過剰にモックを使用していないか？
"""

[pr_code_suggestions]
extra_instructions="""\
1. 【最優先】Google Javascript style guideに従って、次の違反を指摘してください:
   - インデントやスペースの不適切な使用
   - 命名規則の違反
   - 一貫性のないコードスタイル
2. 【重要】ファイル全体の行数が多い (コメント行を含まずに 300 行を超える) 場合、次の観点で分割可能かどうかを確認し、可能であれば指摘してください:
   - コンポーネントや関数の単一責任の原則が守られているか？
   - 重複したロジックがないか？
   - コードの可読性が保たれているか？
3. 【重要】テストコードについて、次の観点でレビューを行い、必要に応じて指摘してください:
   - 主要なユースケースがカバーされているか？
   - エッジケースがテストされているか？
   - 過剰にモックを使用していないか？
"""